import '../modals/product_modal.dart';

int? indexForDetailScreen;

List<Product> products = [
  Product(
    name: "Avodaka Salad",
    price: 20,
    image: "assets/images/food1.png",
    quantity: 0,
    isLike: "false",
    category: "Food",
  ),
  Product(
    name: "Monsoon Salad",
    price: 15,
    image: "assets/images/food2.png",
    quantity: 0,
    isLike: "false",
    category: "Food",
  ),
  Product(
    name: "Royal Salad",
    price: 25,
    image: "assets/images/food3.png",
    quantity: 0,
    isLike: "false",
    category: "Food",
  ),
  Product(
    name: "Fruits Salad",
    price: 10,
    image: "assets/images/food4.png",
    quantity: 0,
    isLike: "false",
    category: "Fruit",
  ),
  Product(
    name: "Loyal Salad",
    price: 28,
    image: "assets/images/food5.png",
    quantity: 0,
    isLike: "false",
    category: "Food",
  ),
  Product(
    name: "Basic Salad",
    price: 10,
    image: "assets/images/food6.png",
    quantity: 0,
    isLike: "false",
    category: "Food",
  ),
  Product(
    name: "All Fruits",
    price: 23,
    image: "assets/images/fruit1.png",
    quantity: 0,
    isLike: "false",
    category: "Fruit",
  ),
  Product(
    name: "Mi Fruits",
    price: 29,
    image: "assets/images/fruit2.png",
    quantity: 0,
    isLike: "false",
    category: "Fruit",
  ),
  Product(
    name: "Unique Fruits",
    price: 40,
    image: "assets/images/fruit3.png",
    quantity: 0,
    isLike: "false",
    category: "Fruit",
  ),
  Product(
    name: "All Grocery",
    price: 100,
    image: "assets/images/gro1.png",
    quantity: 0,
    isLike: "false",
    category: "Grocery",
  ),
  Product(
    name: "Mix Grocery",
    price: 120,
    image: "assets/images/gro2.png",
    quantity: 0,
    isLike: "false",
    category: "Grocery",
  ),
  Product(
    name: "Basic Grocery",
    price: 150,
    image: "assets/images/gro3.png",
    quantity: 0,
    isLike: "false",
    category: "Grocery",
  ),
  Product(
    name: "Crude Grocery",
    price: 220,
    image: "assets/images/gro4.png",
    quantity: 0,
    isLike: "false",
    category: "Grocery",
  ),
  Product(
    name: "All Veges",
    price: 420,
    image: "assets/images/veg2.png",
    quantity: 0,
    isLike: "false",
    category: "Veg",
  ),
  Product(
    name: "Mix Veges",
    price: 580,
    image: "assets/images/veg3.png",
    quantity: 0,
    isLike: "false",
    category: "Veg",
  ),
];
